---
- name: Backup KVStore on desired host
  ansible.builtin.command: |
    {{ splunk_home }}/bin/splunk backup kvstore {{ archive_name | default("") }}
  become: true
  become_user: "{{ splunk_nix_user }}"
  register: splunk_kvstore_backup_out
  changed_when: splunk_kvstore_backup_out.rc == 0
  failed_when: splunk_kvstore_backup_out.rc != 0

- name: Check that backup has finished
  ansible.builtin.command: |
    {{ splunk_home }}/bin/splunk splunk show kvstore-status | grep backupRestoreStatus | sed -r 's/\s+backupRestoreStatus : //g'
  register: splunk_kvstore_status_out
  until: "{{ splunk_kvstore_status_out.stdout }} == 'Ready'"
