---
- name: Destructive KVStore Resync
  block:
  - name: Check if authenticated
    include_tasks: splunk_login.yml
    when: not splunk_authenticated

  # We have to do this first so that we store the captain before removing from the cluster
  - name: Get SHCluster captain
    include_tasks: get_shcluster_captain.yml

  - name: Remove SHCluster member
    ansible.builtin.command: "{{ splunk_home }}/bin/splunk remove shcluster-member"
    register: splunk_remove_shcluster_member
    changed_when: splunk_remove_shcluster_member.rc == 0
    failed_when: splunk_remove_shcluster_member.rc != 0

  - name: Clean KVStore
    include_tasks: adhoc_clean_kvstore.yml

  - name: Add SHCluster member from current member
    ansible.builtin.command: |
      {{ splunk_home }}/bin/splunk add shcluster-member -current_member_uri {{ splunk_shc_captain }}
    register: splunk_remove_shcluster_member
    changed_when: splunk_remove_shcluster_member.rc == 0
    failed_when: splunk_remove_shcluster_member.rc != 0

  become: true
  become_user: "{{ splunk_nix_user }}"
