---
- name: Ensure ufw is installed
  ansible.builtin.package:
    name: ufw
    state: present

- name: Ensure UFW is Started and Enabled
  ansible.builtin.systemd:
    name: ufw
    state: started
    enabled: true

- name: Configure ufw for Splunk
  become: true
  community.general.ufw:
    port: "{{ item.number }}"
    proto: "{{ item.protocol }}"
    rule: allow
  loop: "{{ splunk_firewall_ports }}"
