---
- name: Ensure {{ firewall_service }}  package is installed
  ansible.builtin.package:
    name: "{{ firewall_service }}"
    state: present

- name: Ensure {{ firewall_service }} is Started and Enabled
  ansible.builtin.systemd:
    name: "{{ firewall_service }}"
    state: started
    enabled: true

- name: Configure firewalld for Splunk
  ansible.builtin.template:
    src: firewalld_service.xml.j2
    dest: /etc/firewalld/services/splunk.xml
    backup: true
    mode: 0644
    owner: root
    group: root
  become: true
  notify: reload firewalld
  when: firewall_service == "firewalld"

- name: Configure UFW for Splunk
  community.general.ufw:
    port: "{{ item.number }}"
    proto: "{{ item.protocol }}"
    rule: allow
  become: true
  loop: "{{ splunk_firewall_ports }}"
  when: firewall_service == "ufw"
  notify: reload ufw
